spring:
  rabbitmq:
    host: 192.168.254.151
    port: 5672
    username: admin
    password: admin
#    listener:
#      simple:
#        # 消息预取数
#        prefetch: 1
    cache:
      channel:
        # 如果已达到缓存大小，则等待获取通道的时间。如果为0，则始终创建一个新通道。
        checkout-timeout: 0
        # 要保留在缓存中的通道数。当checkout-timeout>为0时，表示每个连接的最大通道数。
        size: 100
#      connection:
#        # 连接工厂缓存模式 ,默认是 channel
#        mode: connection
#        # 缓存的连接数量，仅在mode 为 connection时有效
#        size: 10
    # 开启spring中的消息退回发布者支持
    publisher-returns: true
    # 开启spring中的发布者消息确认支持
    publisher-confirms: true
    template:
      # 全局默认设置为：消息不可路由强制退回   这个基本没什么用处，因为还需要为RabbitTemplate设置退回回调才行（可以在那里一并设置）
      mandatory: true

# rabbitmq的simple和direct模式的区别：
# simple：底层是开辟了新的线程池去执行处理逻辑，默认使用simple模式
# direct：底层是使用spring底层的线程去执行，如果想节约线程资源可以考虑direct
    listener:
      simple:
#        # 设置消息手动回复
#        acknowledge-mode: manual
        # 订阅失败是否直接停止订阅，默认为true
        missing-queues-fatal: false
#      direct:
        # 订阅失败是否直接停止订阅，默认为false
#        missing-queues-fatal: false
#        prefetch: 0
#      direct:
#        acknowledge-mode: manual
#        prefetch: 1